export const SUBMISSION_INSTRUCTIONS = {
  paragraphs: [
    "Authors are invited to submit papers on original research on Applied Algorithms. Simultaneous submission to a journal or another conference with refereed proceedings is not allowed. Papers must be prepared using LaTeX/LaTeX2e and should not exceed 12 pages in Springer Verlag LNCS style. The LNCS style file must be used without altering margins and font size. The paper must be submitted as a .pdf file using Microsoft CMT. An appendix of a maximum of two pages may be added during submission to include additional results, and this will be read at the discretion of the reviewers.",
  ],
};

export const TOPICS_OF_INTEREST = [
  "Graph Algorithms",
  "Computational Biology",
  "Computational Geometry",
  "Approximation Algorithms",
  "Randomized Algorithms",
  "Spatial Informatics and GIS",
  "Discrete Geometry",
  "Electronic Design Automation",
  "Algorithmic Microfluidics",
  "Social Network Analysis",
  "Cryptography  Network Security",
  "Energy Efficient Algorithms",
  "Quantum Computing",
  "Number Theoretic Algorithms",
  "Machine Learning Algorithms",
  "Deep Learning Algorithms",
  "Reinforcement Learning Algorithms",
  "Heuristic Search",
  "Generative AI",
  "Recommender Systems",
  "Image Processing",
  "Natural Language Processing",
  "Computer Vision",
  "Data Mining",
  "Logic and Reasoning",
  "Optimization Algorithms",
  "Robotics",
  "Neuromorphic Computing",
];