export const SUBMISSION_INSTRUCTIONS = {
  paragraphs: [
    "Authors are invited to submit papers on original research on Applied Algorithms. Simultaneous submission to a journal or another conference with refereed proceedings is not allowed. Papers must be prepared using LaTeX/LaTeX2e and should not exceed 12 pages in Springer Verlag LNCS style. The LNCS style file must be used without altering margins and font size. The paper must be submitted as a .pdf file using Microsoft CMT. An appendix of a maximum of two pages may be added during submission to include additional results, and this will be read at the discretion of the reviewers.",
  ],
};

export const TOPICS_OF_INTEREST = [
  "Graph Algorithms",
  "Computational Biology",
  "Computational Geometry",
  "Approximation Algorithms",
  "Randomized Algorithms",
  "Spatial Informatics and GIS",
  "Discrete Geometry",
  "Electronic Design Automation",
  "Algorithmic Microfluidics",
  "Social Network Analysis",
  "Cryptography  Network Security",
  "Energy Efficient Algorithms",
  "Quantum Computing",
  "Number Theoretic Algorithms",
  "Machine Learning Algorithms",
  "Deep Learning Algorithms",
  "Reinforcement Learning Algorithms",
  "Heuristic Search",
  "Generative AI",
  "Recommender Systems",
  "Image Processing",
  "Natural Language Processing",
  "Computer Vision",
  "Data Mining",
  "Logic and Reasoning",
  "Optimization Algorithms",
  "Robotics",
  "Neuromorphic Computing",
];

export interface ImportantPoint {
  text: string;
  link?: { label: string; url: string };
  subPoints?: { text: string }[];
}

export const IMPORTANT_POINTS: ImportantPoint[] = [
  {
    text: "Please familiarize yourself with the",
    link: {
      label: "Springer Nature Code of Conduct",
      url: "https://www.springernature.com/gp/authors/book-authors-code-of-conduct",
    },
  },
  {
    text: "Please ensure that you address the reviewers' comments in your camera-ready submission (limited to 12 pages). Review comments can be viewed with paper status in CMT.",
  },
  {
    text: "Please ensure that your final camera-ready submission is within 10% overall similarity, with less than 2% from a single source, for being eligible to be published by Springer.",
  },
  {
    text: "Please format your paper within 12 pages according to the",
    link: {
      label: "Springer LNCS Guidelines",
      url: "https://link.springer.com/series/558/information-for-authors-and-editors",
    },
  },
  {
    text: "The same template can be accessed via the LNCS template on the",
    link: {
      label: "Overleaf website",
      url: "https://www.overleaf.com/latex/templates/springer-lecture-notes-in-computer-science/kzwwpvhwnvfj#.WsdHOy5uZpg",
    },
  },
  {
    text: `Author Names: These should be written out in full in the header of the paper. They are shortened by Springer Production to "initials surname" in the running heads and take the form "surname, given name" in the author index. If you or any of your co-authors have more than one family name, it should be made clear how your name is to be displayed in the running heads and the author index. All authors should write their given names in front of their surnames at the tops of their papers. If you only have one (main) name, please make sure that this name is written out in full in the running heads, when you check your final PDF. Also, if you have more than one paper in the volume, please check that your name has been written consistently throughout.`,
  },
  {
    text: "Each corresponding author will be asked to:",
    subPoints: [
      {
        text: "Sign Springer's License-to-Publish form online on behalf of their coauthors, as a part of the upload process.",
      },
      { text: "Upload the camera-ready version of the paper as a PDF." },
      {
        text: "Upload source file packages, which will include all source files (LaTeX bundle in a single zip file) and all figure sources, required for Springer's production editing process.",
      },
    ],
  },
  {
    text: "Please carefully prepare your files for upload as per the following guidelines. You must upload four required files with the following naming convention:",
    subPoints: [
      { text: "PIDXXX-source.zip: Camera-ready source ZIP file" },
      {
        text: "PIDXXX.pdf: Camera-ready PDF file generated by the source material contained in PIDXXX-source.zip",
      },
      { text: "PIDXXX-rtr.pdf: Response to reviewers' comments" },
      {
        text: "PIDXXX-pmnt.pdf: Payment Confirmation (screenshot) containing the UTR/Ref number from the registration application/process.",
      },
      {
        text: "We request that all authors fill up the License to Publish / Copyright form and upload it to your CMT author console.",
      },
    ],
  },
  {
    text: "Upload all the above mentioned files to the CMT submission portal. Also, email us the same files at",
    link: { label: "icaa@heritageit.edu", url: "mailto:icaa@heritageit.edu" },
  },
  {
    text: "Ensure that all authors' names and affiliations are accurate in the final version.",
  },
];